# Generated by Django 4.2.7 on 2025-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_doctornote_is_visible_to_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
